In [2]:
import numpy as np

### Вычисления с помощью Numpy

In [12]:
b = ([1, 6], [2, 8],[3, 11], [3, 10], [1,7])

In [13]:
a = np.array(b)

In [14]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [16]:
a.mean(axis=0)

array([2. , 8.4])

In [17]:
mean_a = a.mean(axis=0)

In [18]:
mean_a

array([2. , 8.4])

In [20]:
a_centered = np.array(a - mean_a)

In [23]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [29]:
a_centered_sp = np.dot([-1,0,1,1,-1],[-2.4,-0.4,2.6,1.6,-1.4])

In [31]:
a_centered_sp

8.0

In [32]:
acenteredsp = a_centered_sp / 2

In [33]:
acenteredsp

4.0

### Работа с данными в Pandas

In [36]:
import pandas as pd

In [38]:
authors = pd.DataFrame({'author_id':[1,2,3], 'author_name':['Тургенев', 'Чехов', 'Островский']})

In [40]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [42]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price' : [450, 300, 350, 500, 450, 370, 290]}, columns = ['author_id', 'book_title', 'price'])

In [43]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [45]:
authors_price = pd.merge(authors,book, on = 'author_id')

In [47]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [48]:
top5 = authors_price.nlargest(5,'price')

In [50]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [ ]:
authors_stat = pd.DataFrame({authors_price['author_name'], authors_price['price'].min(), authors_price['price'].max(), authors_price['price'].mean()}, 
                            columns = [ 'author_name', 'min_price', 'max_price', 'mean_price'])